"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Banknote, CreditCard, QrCode, WalletCards, LockKeyhole, UnlockKeyhole, RefreshCw } from "lucide-react";
import { supabase } from "@/lib/supabaseClient";

const LOJA_SLUG="drogariasporto-loja2";
function brl(n:number){return Number(n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}

type Sessao={id:string;operador:string|null;valor_abertura:number|null;valor_contado:number|null;status:string;aberto_em:string;fechado_em:string|null};
type Pg={id:string;venda_id:string;forma:string;valor:number;created_at:string};

export default function PortoCaixa(){
 const [sessao,setSessao]=useState<Sessao|null>(null); const [pagamentos,setPagamentos]=useState<Pg[]>([]); const [operador,setOperador]=useState(""); const [abertura,setAbertura]=useState("200"); const [contado,setContado]=useState(""); const [loading,setLoading]=useState(true);
 async function carregar(){setLoading(true);const {data:s,error}=await supabase.from("porto_caixa_sessoes").select("*").eq("loja_slug",LOJA_SLUG).eq("status","aberto").order("aberto_em",{ascending:false}).limit(1).maybeSingle();if(error)console.error(error);setSessao(s as Sessao|null);if(s){const {data:p,error:ep}=await supabase.from("porto_venda_pagamentos").select("id,venda_id,forma,valor,created_at").eq("caixa_sessao_id",s.id).order("created_at",{ascending:true});if(ep)console.error(ep);setPagamentos((p||[]) as Pg[])}else setPagamentos([]);setLoading(false)}
 useEffect(()=>{carregar()},[]);
 const totais=useMemo(()=>pagamentos.reduce((a,p)=>{a[p.forma]=(a[p.forma]||0)+Number(p.valor||0);a.Total+=Number(p.valor||0);return a},{Dinheiro:0,Pix:0,"Débito":0,"Crédito":0,Total:0} as Record<string,number>),[pagamentos]);
 const esperado=Number(sessao?.valor_abertura||0)+Number(totais.Dinheiro||0); const diferenca=(Number(contado||0)||0)-esperado;
 async function abrir(){if(!operador.trim())return alert("Informe o operador.");const {error}=await supabase.from("porto_caixa_sessoes").insert({loja_slug:LOJA_SLUG,operador:operador.trim(),status:"aberto",valor_abertura:Number(abertura||0),aberto_em:new Date().toISOString()});if(error)return alert(error.message);setOperador("");await carregar()}
 async function fechar(){if(!sessao)return; if(contado==="")return alert("Informe o dinheiro contado no caixa físico.");const resumo={dinheiro:Number(totais.Dinheiro||0),pix:Number(totais.Pix||0),debito:Number(totais['Débito']||0),credito:Number(totais['Crédito']||0),total:Number(totais.Total||0),qtd_pagamentos:pagamentos.length,esperado_dinheiro:esperado,contado:Number(contado||0),diferenca};const {error}=await supabase.from("porto_caixa_sessoes").update({status:"fechado",fechado_em:new Date().toISOString(),valor_contado:Number(contado||0),valor_fechamento:esperado,diferenca,resumo_pagamentos:resumo}).eq("id",sessao.id);if(error)return alert(error.message);alert("Caixa fechado. Totais foram consolidados automaticamente a partir das vendas.");setContado("");await carregar()}
 const cards=[['Dinheiro',totais.Dinheiro,Banknote],['Pix',totais.Pix,QrCode],['Débito',totais['Débito'],CreditCard],['Crédito',totais['Crédito'],WalletCards]] as const;
 return <main className="min-h-screen bg-slate-100 p-4 md:p-6"><div className="mx-auto max-w-[1300px]">
  <header className="flex items-center justify-between rounded-2xl bg-blue-900 p-4 text-white"><div><p className="text-xs font-bold text-blue-200">DROGARIAS PORTO • LOJA 2</p><h1 className="text-2xl font-black">Caixa e Fechamento</h1></div><div className="flex gap-2"><Link href="/drogariasporto/pdv" className="rounded-xl bg-white/10 p-2"><ArrowLeft/></Link><button onClick={carregar} className="rounded-xl bg-white/10 p-2"><RefreshCw/></button></div></header>
  {loading?<div className="p-10 text-center">Carregando caixa...</div>:!sessao?<section className="mx-auto mt-8 max-w-xl rounded-2xl bg-white p-6 shadow-sm"><div className="mb-5 flex items-center gap-3"><div className="rounded-xl bg-green-100 p-3 text-green-700"><UnlockKeyhole/></div><div><h2 className="text-xl font-black">Abrir caixa</h2><p className="text-sm text-slate-500">A sessão passa a receber automaticamente todas as vendas do PDV.</p></div></div><label className="text-sm font-bold">Operador</label><input value={operador} onChange={e=>setOperador(e.target.value)} className="mt-1 w-full rounded-xl border p-3" placeholder="Nome do operador"/><label className="mt-4 block text-sm font-bold">Fundo de abertura</label><input value={abertura} onChange={e=>setAbertura(e.target.value)} className="mt-1 w-full rounded-xl border p-3" inputMode="decimal"/><button onClick={abrir} className="mt-6 w-full rounded-xl bg-green-600 py-4 font-black text-white">ABRIR CAIXA</button></section>:
  <><div className="mt-6 grid gap-3 md:grid-cols-5">{cards.map(([nome,val,Icon])=><div key={nome} className="rounded-2xl bg-white p-4 shadow-sm"><Icon className="text-blue-700"/><p className="mt-3 text-sm font-bold text-slate-500">{nome}</p><p className="text-2xl font-black">{brl(Number(val||0))}</p></div>)}<div className="rounded-2xl bg-blue-900 p-4 text-white shadow-sm"><p className="text-sm font-bold text-blue-200">TOTAL VENDIDO</p><p className="mt-3 text-3xl font-black">{brl(Number(totais.Total||0))}</p><p className="mt-2 text-xs text-blue-200">{pagamentos.length} pagamentos registrados</p></div></div>
  <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_430px]"><section className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Vendas recebidas automaticamente</h2><p className="text-sm text-slate-500">Cada linha veio de uma venda finalizada no PDV.</p></div></div><div className="mt-4 overflow-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="p-3">Venda</th><th>Forma</th><th>Valor</th><th>Horário</th></tr></thead><tbody>{pagamentos.map(p=><tr key={p.id} className="border-t"><td className="p-3 font-mono">{p.venda_id.slice(0,8)}</td><td className="font-bold">{p.forma}</td><td>{brl(p.valor)}</td><td>{new Date(p.created_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</td></tr>)}</tbody></table></div></section>
  <aside className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><LockKeyhole className="text-red-600"/><h2 className="text-xl font-black">Fechamento</h2></div><div className="mt-5 space-y-3 rounded-xl bg-slate-50 p-4 text-sm"><div className="flex justify-between"><span>Fundo inicial</span><b>{brl(Number(sessao.valor_abertura||0))}</b></div><div className="flex justify-between"><span>+ Vendas em dinheiro</span><b>{brl(Number(totais.Dinheiro||0))}</b></div><div className="border-t pt-3 flex justify-between text-base"><span>Dinheiro esperado</span><b>{brl(esperado)}</b></div></div><label className="mt-5 block text-sm font-bold">Dinheiro contado fisicamente</label><input value={contado} onChange={e=>setContado(e.target.value)} className="mt-1 w-full rounded-xl border p-3 text-lg font-bold" placeholder="0,00" inputMode="decimal"/>{contado!==""&&<div className={`mt-3 rounded-xl p-3 text-center font-black ${Math.abs(diferenca)<0.01?'bg-green-100 text-green-700':'bg-red-100 text-red-700'}`}>Diferença: {brl(diferenca)}</div>}<button onClick={fechar} className="mt-5 w-full rounded-xl bg-red-600 py-4 font-black text-white">FECHAR CAIXA</button><p className="mt-3 text-xs text-slate-500">Pix, débito e crédito não entram no dinheiro físico; ficam consolidados no resumo financeiro.</p></aside></div></>}
 </div></main>
}
